### ISSUE TITLE
Regression in Stabilizer

### ISSUE THREAD

**Issue by mohamed-barakat** [gap-packages/ferret#62]
The following code used to work very fast:

```
gap> LoadPackage( "ferret" );;
gap> L := [ [ 1, 2, 3, 4 ], [ 1, 5, 6, 7 ], [ 1, 8, 9, 10 ], [ 2, 5, 8, 11 ], [ 2, 6, 9, 12 ], [ 3, 5, 10, 13 ], [ 3, 11, 12, 14 ], [ 4, 7, 8, 14 ] ];;
gap> Stabilizer( SymmetricGroup( 14 ), L, OnSetsSets );
```

Now it does not terminate in a reasonable time. It seems that `Stabilizer` eventually leaves `ferret` and executes interpreted GAP code.

**Comment by wilfwilson** [comment]
Thank you for the report.

My somewhat-related advertising: @ChrisJefferson has more recently been working on the Vole package, which is available at https://peal.github.io/vole

My understanding is that the functionality of Vole is a superset of the functionality of ferret, and that the performance of Vole should, roughly speaking, be better than the functionality for ferret (at least eventually).

So if you're struggling with ferret, you might have better results with Vole:
```
gap> LoadPackage( "vole" );;
gap> L := [ [ 1, 2, 3, 4 ], [ 1, 5, 6, 7 ], [ 1, 8, 9, 10 ], [ 2, 5, 8, 11 ], [ 2, 6, 9, 12 ], [ 3, 5, 10, 13 ], [ 3, 11, 12, 14 ], [ 4, 7, 8, 14 ] ];;
gap> Vole.Stabilizer( SymmetricGroup( 14 ), L, OnSetsSets );
Group(())
gap> time;
3
```

**Comment by mohamed-barakat** [comment]
Thank you very much, Wilf. As far as I can see, `Vole` is not (yet) distributed with GAP, right?

**Comment by ChrisJefferson** [comment]
Thanks for the report!

At some point I tried to not send some "trivial" problems (like stabilizing a set, or a tuple, of ints in the symmetry group) to ferret, as GAP has special members to solve them, but I accidentally sent the (much harder) set of sets in the symmetric group also to GAP.

I've now tightened up the check to only send a small set of things to GAP. New release (1.0.13) should appear soon.

I plan to distribute vole with GAP very soon (we are in the process of removing some dependancies on packages we don't want to release). When it's packaged in GAP, I'll send you a message so you can take a look. In vole, we (like in the example above) require writing `Vole.Stabilizer`, because hooking into normal `Stabilizer` (like we do in ferret) has always been a bit arkward (and would get more arkward if both ferret and vole were trying to do it).

**Comment by ChrisJefferson** [comment]
Now fixed in latest release (will take a couple of days to make it to the updated GAP packages archive)

**Comment by mohamed-barakat** [comment]
Awesome. Thank you very much. And please inform me once `Vole` is deposited with GAP.
